name: Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.3.0
        native-image: true
    - name: Build
      run: mvn clean package #TODO verify -Pfailsafe
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: target-linux
        path: ./target
        retention-days: 5

  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.3.0
        native-image: true
    - name: Build with Maven
      run: ./mvnw.cmd clean package #TODO verify -Pfailsafe
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: target-windows
        path: ./target
        retention-days: 5
